### ISSUE TITLE
Dotazeni migrace DB extraktoru

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-extractor-common#4]
# DB Extraktory
- [MySQL](https://github.com/keboola/db-extractor-mysql)
- [MSSQL](https://github.com/keboola/db-extractor-mssql)
- [PgSQL](https://github.com/keboola/db-extractor-pgsql)
- [Oracle](https://github.com/keboola/db-extractor-oracle)
- [Impala](https://github.com/keboola/db-extractor-impala)
- [Firebird](https://github.com/keboola/db-extractor-firebird)
- [DB2](https://github.com/keboola/db-extractor-db2)
- [DB2 (Bata)](https://github.com/keboola/db-extractor-db2-bata)
- [Mongo](https://github.com/keboola/mongodb-extractor)
## TODO
- [x] Sync API call _Test Credentials_ (caka na implementaci v docker-bundle)
- [x] Password encrypt
- [x] Pripravit migraciu
- [x] Post na status, ze stary extraktor je deprecated
- [x] Skryt stary extraktor z ponuky
- [ ] Vyhodit stary extraktor (po 2 mesiacoch napr)

**Comment by Halama** [comment]
@MiroCillik jak to vypada, je nejakej progress? :)

**Comment by MiroCillik** [comment]
@Halama implementoval som ten Test Connection api call do db-extractor-common, teraz sa mozu updatnut vsetky extraktory a moze sa to vypustit ak bude vsetko fungovat :)

**Comment by Halama** [comment]
ok, neni to nasazene na zadnem zatim teda?

**Comment by MiroCillik** [comment]
je updatnuty Firebird vo verzi 1.4.0 ale v KBC som ho este nezapinal / nezkusal to, lebo som nemal moc cas a nechcel som to nahodou tam nechat rozbite. Ten Firebird pouziva jeden projekt.

**Comment by Halama** [comment]
v pohode, tak pristi tyden se to dotahne

**Comment by ErikZigo** [comment]
MySQL, Oracle, MSSQL maj test credentials implementovany a nasazeny

@MiroCillik do dalsich to muzu pridat

**Comment by MiroCillik** [comment]
Vsetky extraktory (okrem db2 pre Batu) su updatnute, takze podporuju Test Connection Action.
Pracujem na komponente na migraciu konfiguraci.

**Comment by Halama** [comment]
a z ui pro test credentials to vypada jak? Jakmile bude tak se muzou ty extraktory vypublikovat a stare schovat z nabidky.

**Comment by MiroCillik** [comment]
Nebudeme cakat na tu migraci?

**Comment by Halama** [comment]
ne, ta migrace se muze objevit potom.

**Comment by MiroCillik** [comment]
OK!

**Comment by Halama** [comment]
Potrebuejme co nejrychleji zaridit at uz nikdo ted nezaklada stary, aby ho za par dni nemigroval zbytecne.

**Comment by MiroCillik** [comment]
jj, pravda

**Comment by Halama** [comment]
Takze postup asi takhle:
 - Nove extraktory se nastavi jako public (predtim se poradne otestuji)
 - Stary se oznaci deprecated a do jeho long description se napise neco jako ze pripravujeme migracni tool, ze uz to i rucne muzou zmigrovat na novy - bude tam nabidka novych extraktoru. Asi by tam mohlo byt i nejake datum konce toho stareho. 
 - Info na status o tom ze jsou nove, stary je deprecated atd. vlastne zhruba to same co bude v long description toho deprecated.

**Comment by MiroCillik** [comment]
ok

**Comment by Halama** [comment]
- https://github.com/keboola/kbc-ui/issues/571
- https://github.com/keboola/kbc-ui/issues/572
- sifrovani hesla

**Comment by kacurez** [comment]
tak tie issues vcetne sifrovaneho hesla su vyriesene.

**Comment by MiroCillik** [comment]
Je pripraveny migracny tool https://github.com/keboola/config-migration-tool/blob/master/README.md
@kacurez Mozes k tomu spravit UI. 
Teraz je to spravene tak, alebo ja si to tak predstavujem, ze uzivatel klikne "ze chce zmigrovat konifgy".
V config-migration-tool komponente sa zalozi nova konfiguracia, ktora vyzera takto:
``` yaml
parameters:
  component: 'ex-db'
  projectId: 395
  token: *INSERT_SAPI_TOKEN_HERE*
```
A tato konfiguracia sa spusti (prebehne migracia) a ked job stastne skonci, konfiguracia sa zase zmaze. A tym aj zmizne tato komponenta uzivatelovi z projektu. Moze to takto byt?

**Comment by kacurez** [comment]
Docker komponentu je mozne pustit aj bez configu, tj mu to nacpes rovno do tela run requestu v `configData` property. Nevidim dovod kvoli tomu zakladat konfig. A paremtre bude vidno v detaile jobu ak bude treba kontrola.

Token by bolo lepsie tlacit cez docker-bundle(env variable) a z toho vlastne ziskat aj projektId nie? Takze by jedinym parametrom bol `component`.

**Comment by MiroCillik** [comment]
Dobre spravim to ako pises.

**Comment by MiroCillik** [comment]
@kacurez upravil som to, token beriem z ENV, takze staci parameter component, ktory bude v tomto pripade vzdy 'ex-db'. Takze sa do toho mozes pustit ;)

**Comment by kacurez** [comment]
@MiroCillik narazil som na chybu v matrixe, ked pustim uz zmigrovany konfig tak mi skonci s chybou:
`Invalid type for path "parameters.tables.0.incremental". Expected boolean, but got string. [] []`
tj asi sa spatne zkonvertoval incremental.

Chce to ma poridne testy imo a nato by sa dobre hodilo generativne testovanie: Specifikujes vlastnosti vstupu(tj vlastnosti jedneho konfigu), potom sa na zaklade tychto vlastnosti budu nahodne generovat konfigy, kt sa dalej zmigruju a porovnaju s povodny(vygenerovanym) konfigom. Imho by sa to dalo takto urobit.

**Comment by MiroCillik** [comment]
@kacurez jo, tiez som si to vsimol. Diky. Nad niecim takym (generative testovanie) som rozmyslal, spravim to tak asi.

**Comment by MiroCillik** [comment]
@kacurez nasadil som novu verziu, kde je to poriesene a tiez v odpovedi "status" action je to componentId nove.

**Comment by kacurez** [comment]
@MiroCillik ten dialog s updatovnym statusom o componentId a text je pripraveny a nasadeny. Chcelo by to este status o updatovanych orchestraciach.

**Comment by MiroCillik** [comment]
@kacurez priprdnem tie orchestracie do odpovede `status` akcie.

**Comment by pivnicek** [comment]
@MiroCillik zaviram tohle, nevadi?

**Comment by MiroCillik** [comment]
Jasne, v pohode
